-- Migration v1.9: Add invite codes to groups (single-use)
-- Run this in Supabase SQL Editor if upgrading from v1.8.x

-- Add invite code fields to groups table
ALTER TABLE public.groups 
  ADD COLUMN invite_code TEXT UNIQUE,
  ADD COLUMN used_by_user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
  ADD COLUMN used_at TIMESTAMP WITH TIME ZONE;

-- Create index for fast lookup by invite code
CREATE INDEX idx_groups_invite_code ON public.groups(invite_code);

-- Comments
COMMENT ON COLUMN public.groups.invite_code IS 'Unique invite code for joining group (single-use)';
COMMENT ON COLUMN public.groups.used_by_user_id IS 'User who used the invite code (NULL if not used yet)';
COMMENT ON COLUMN public.groups.used_at IS 'Timestamp when invite code was used';

-- Note: Existing groups will have invite_code = NULL
-- Codes are generated on group creation or can be regenerated by owner
